### ISSUE TITLE
Support other map layouts

### ISSUE THREAD

**Issue by Yoduh** [ti-assistant/issues#2]
I would love to see different map layouts possible such as the ones supported by certain map generators, e.g. https://joepinion.github.io/ti4-map-lab/ or 
https://keeganw.github.io/ti4/?settings=F42006907FFF

Which can generate maps like the 4-player skinny/vertical map, among others.
![ti4-map (1)](https://user-images.githubusercontent.com/6708383/235380582-ae8c82c7-e533-47d1-a133-9c4aa886ac69.png)

When I feed ti-assistant the map string it still puts the home system tiles in standard 6 player map positions

**Comment by SephHawkins** [comment]
I added support for the following maps from the TI4 map lab:

- 4 player skinny map
- 4 player warp map

Are there other maps that you'd like to see added? Happy to add more if you'd like them.

**Comment by BuzZoiDk24** [comment]
I'm pretty sure it would be very difficult or even impossible to implement, but it would be nice to have the framework/grid of a galaxy available (like in the TTS version) and allow custom placing of tiles. I believe this would make any TTS string work and maybe there are even possibilities to implement the map building step into the app, letting players taking turns to build it. 

That being said, as already mentioned it sounds quite extensive to code or it might be impossible due to other reasons.

**Comment by SephHawkins** [comment]
It's definitely not impossible - I mostly haven't prioritized it because there are a number of good map builders out there.

That being said, it might be useful, so I'll take a pass on figuring out how much work it would be.

**Comment by SephHawkins** [comment]
Marking as fixed since there's now a map builder (which can be used to create any possible layout).
