### ISSUE TITLE
Improve Visual Indication for Players Passing

### ISSUE THREAD

**Issue by GrantWasil** [ti-assistant/issues#22]
Currently, when a player passes on their turn, it turns the color of their name to Gray. This isn't the most obvious way of indicating that a player has passed and our group was having a hard time distinguishing who has passed and hasn't. 

We would propose doing a small strike through of the name of the player and doing something similar with the action card, or adding a small icon to indicate this. 

Thanks for your help!

**Comment by SephHawkins** [comment]
Good point. Looking at it with a strike-through, I'm not sure that that it makes it that much clearer, but I'm sure there's some solution that can be had.

Just to help me understand, was the issue that players were unprepared because they didn't know how long it was going to be until their next turn or was the issue that players wanted to know whether or not a specific other player had passed and couldn't?

**Comment by SephHawkins** [comment]
Closing this - I've made several minor changes to make it easier to tell which players have passed and which are still taking turns.
