### ISSUE TITLE
Xxcha Commander Bug?

### ISSUE THREAD

**Issue by willcarey119** [ti-assistant/issues#37]
Had a game this past Saturday (https://ti-assistant.com/game/9FhFXv/main)that included Xxcha (and Mahact) and TI-Assistant seemed to struggle with both aspects of Xxcha's commander "Game components cannot prevent you from voting" and "each planet you exhaust adds one additional vote" as well as the total voting power provided by the hero.

The second aspect of the commander and the hero are less of an issue since they can be managed with the extra votes field. The lack of transparent voting power is a little bit of a pain, but nothing manageable. 

The "game components cannot prevent you from voting" bit is the key reason for this post. Whenever Xxcha and Mahact wanted to play a rider and vote it kind of threw the process of using TI-Assistant for a loop. We got by by not recording the riders as we played, but it was an interesting interaction. 

Thanks again for the great website!

**Comment by SephHawkins** [comment]
Thanks for reporting this! There's a few different issues here.

- [ ] Xxcha's commander only gets marked as unlocked by manually doing so on the Xxcha info popup. It'd be possible to detect the condition (planets w/ 12 influence), but there's a lot of edge cases to handle with that. Might be better to have a more explicit popup for managing leaders/alliances.
- [ ] There's no way to mark that a faction has another faction's alliance (or in the case of Mahact, their token). This could also be resolved by that explicit popup.
- [x] It should probably be possible to "override" some of the blocks (cannot vote, cannot score publics, etc.) so that players don't need to know how to resolve things (e.g. Knowing that they need to open the "Leaders" menu to allow Mahact to play a rider and vote).

I'll take a pass on resolving these when I have a chance.

**Comment by buedefixe** [comment]
Love the tool and came here to report something similar, so I figured I'd keep it in this thread.

Really appreciate adding the option to manually allow voting!

You're probably already aware, but based on your issues as stated above, it wasn't 100 percent clear to me. Just to be explicitly clear, in the current app, even if the Xxcha commander is manually unlocked in the Xxcha info popup, it doesn't add the planet count as available Xxcha bonus votes.

Also for Xxcha, even when the hero is manually unlocked, it doesn't include the resource values in the influence total.

For Hacan, even when the commander is manually unlocked, there's nothing to indicate that their trade goods are available extra votes, which would be nice (I realize tracking trade goods in the app would be silly, but maybe something like "🪙x2" shows up for them when their commander is unlocked (and for whoever has access to their commander if/when alliance/mahact functionality is added)

I also think it would be nice to somewhere show the grand total of Available votes across all factions, especially a dynamic Total Available Votes Remaining would be a bit of a time saver as people try to figure out if there are enough votes left to swing things.

One final suggestion related to agendas is that it would be nice if the the "Laws in Effect" button could have a counter. I.e. say "1 Law in Effect" or "2 Laws in Effect" etc. instead of just "Laws in Effect." There are a number of minor reasons why having that number easily visible would be nice, but especially for keeping track of the secret objective.

Again, fantastic app and thanks for being so open to feedback!

**Comment by SephHawkins** [comment]
Thanks for reporting all these issues - I really appreciate it!

> even if the Xxcha commander is manually unlocked in the Xxcha info popup, it doesn't add the planet count as available Xxcha bonus votes.
> Also for Xxcha, even when the hero is manually unlocked, it doesn't include the resource values in the influence total.

This looks like a bug, it's definitely supposed to. Filed #56 to track these separately.

> For Hacan, even when the commander is manually unlocked, there's nothing to indicate that their trade goods are available extra votes

That's a good idea for displaying something there. I'll have to play around with things to see if I can come up with something that looks good and doesn't take up too much space. Added to #56 as well.

> I also think it would be nice to somewhere show the grand total of Available votes across all factions, especially a dynamic Total Available Votes Remaining would be a bit of a time saver as people try to figure out if there are enough votes left to swing things.

Definitely doable, and you're right that it would be useful - filed #57 to track that.

> One final suggestion related to agendas is that it would be nice if the the "Laws in Effect" button could have a counter. I.e. say "1 Law in Effect" or "2 Laws in Effect" etc. instead of just "Laws in Effect." There are a number of minor reasons why having that number easily visible would be nice, but especially for keeping track of the secret objective.

Totally agree - and is a super simple change. I'll add that in the next chance I get.

**Comment by SephHawkins** [comment]
#56 is now fixed, and the "Laws in Effect" now displays the number of laws.

Closing this since #57 and #58 track the remaining changes for this.
